name: Deploy to Demo Environment

on:
  push:
    branches: [ demo ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, zip, gd, exif, intl, bcmath, soap, pdo_mysql
        coverage: none
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      
    - name: Deploy to Demo Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEMO_HOST }}
        username: ${{ secrets.DEMO_USERNAME }}
        key: ${{ secrets.DEMO_SSH_KEY }}
        port: ${{ secrets.DEMO_PORT }}
        script: |
          cd /home/u242329769/domains/demo.kashtre.com/public_html
          git fetch origin
          git reset --hard origin/demo
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
          php artisan db:seed --force
          chmod -R 755 storage bootstrap/cache
          chown -R u242329769:u242329769 storage bootstrap/cache
          
    - name: Clear Demo Cache
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEMO_HOST }}
        username: ${{ secrets.DEMO_USERNAME }}
        key: ${{ secrets.DEMO_SSH_KEY }}
        port: ${{ secrets.DEMO_PORT }}
        script: |
          cd /home/u242329769/domains/demo.kashtre.com/public_html
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          
    - name: Notify Deployment Success
      if: success()
      run: |
        echo "✅ Deployment to demo.kashtre.com completed successfully!"
        echo "🌐 Demo site: https://demo.kashtre.com"
        
    - name: Notify Deployment Failure
      if: failure()
      run: |
        echo "❌ Deployment to demo.kashtre.com failed!"
        echo "Please check the logs for more details."
