name: Deploy Staging Branch to Hostinger (Root)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Staging Branch
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, ctype, json, tokenizer, curl
          coverage: none

      # Step 3: Install sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Step 4: Deploy to Hostinger via SSH
      - name: Deploy to Hostinger
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Define deployment directory
          DEPLOY_DIR="/home/u242329769/domains/staging.kashtre.com/public_html"

          # Copy files using rsync with sshpass, excluding unnecessary files
          echo "Starting file transfer with rsync..."
          sshpass -p "$FTP_PASSWORD" rsync -avz --delete \
            --exclude '.env' \
            --exclude '.htaccess' \
            --exclude 'node_modules/' \
            --exclude '.git/' \
            --exclude 'tests/' \
            --exclude '.DS_Store' \
            --exclude '*.log' \
            --exclude 'storage/logs/' \
            --exclude 'storage/framework/cache/' \
            --exclude 'storage/framework/sessions/' \
            --exclude 'storage/framework/views/' \
            --exclude 'vendor/' \
            -e "ssh -p 65002 -o StrictHostKeyChecking=no" \
            $GITHUB_WORKSPACE/ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:"$DEPLOY_DIR"
          
          echo "File transfer completed successfully"

          # Run post-deployment setup
          echo "Running post-deployment setup..."
          sshpass -p "$FTP_PASSWORD" ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} bash -c '
            DEPLOY_DIR="/home/u242329769/domains/staging.kashtre.com/public_html"
            cd "$DEPLOY_DIR"

            # Install Composer dependencies with ignore platform requirements
            echo "Installing Composer dependencies..."
            composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs --prefer-dist

            # Set permissions
            chmod -R 755 storage bootstrap/cache

            # Clear all caches
            echo "Clearing caches..."
            php artisan optimize:clear || echo "Cache clear failed but continuing"

            # Run migrations
            echo "Running migrations..."
            php artisan migrate --force || echo "Migration failed but continuing"

            # Run seeders
            echo "Running seeders..."
            php artisan db:seed --class=MoneyAccountsSeeder --force || echo "MoneyAccountsSeeder failed but continuing"
            php artisan db:seed --class=CityHealthClinicItemsSeeder --force || echo "CityHealthClinicItemsSeeder failed but continuing"

            # Create storage link
            php artisan storage:link || echo "Storage link already exists"

            # Final optimization
            echo "Final optimization..."
            php artisan optimize || echo "Optimize failed but continuing"

            # Verify deployment
            echo "Deployment verification:"
            php artisan --version || echo "Artisan not working"
            echo "Deployment completed!"
          ' 